### ISSUE TITLE
[BUG] pymaker2 project downloads to incorrect folder 

### ISSUE THREAD

**Issue by Josverl** [pycom/pymakr-vsc#258]
## The bug
The download destination folder is malformed / concatenated when  downloading

**To Reproduce**
1. Upload a project to an MCU from a workspace folder 
    './minified'
3. run a script that created a folder structure ; something like :  
    - /stubs
    - /stubs/micropython-v1_19_1-esp8266  
    - /stubs/micropython-v1_19_1-esp8266/zlib.py  
4. Download the project 
5. the MCU's `/stubs`  folder  in not downloaded to the `./minified/stubs` folder but to the `.minifiedstubs` folder

**Expected behavior**
downloaded folder structure to be located inside the project folder 

**Screenshots**
![image](https://user-images.githubusercontent.com/981654/174630400-c6e1f25a-e0e4-47ea-8dd2-3d513f671ecc.png)

![image](https://user-images.githubusercontent.com/981654/174631827-87e7f4c5-6c1e-47b2-a1ef-24aaf3a7827d.png)

**Desktop (please complete the following information):**

* Pymakr:  preview 2.18.0
* micropython 1.19.1 esp8266
* MCU root folder : `/`
*

Version: 1.68.1 (user setup)
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:48:58.283Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by jakobrosenberg** [comment]
Thanks for reporting this. I wasn't able to replicate the issue on my Pycom devices. I suspect the issue is the root path.

When files are downloaded, the root path is stripped from the source. This means `/flash/myfile.py` without `/flash` becomes `/myfile.py`, but `/myfile.py` without `/` becomes `myfile.py`.

I've updated the script to replace root path plus trailing slashes with a single slash to ensure we have a separator. Will push a fix now.
