### ISSUE TITLE
switch version numbering to X.Y.0

### ISSUE THREAD

**Issue by Josverl** [pycom/pymakr-vsc#39]
# Feature Request 🚀

Could you change the version numbering from `1.0.7` to `1.7.0` please ?
ie use the `<Major>.<Minor>.<Patch>` schema .

That would allow me and other co-authors to use increasing patch numbers  ( ie `1.7.1 … 1.7.99` , and still automatically get updated when there is a pycom release of a next `<Minor>` version i.e. `1.8.0`.

In addition it may help aligning the Major & Minor version numbers between VSCode and Atom Add-ins.

/jos

**Comment by RalphHogenbirk** [comment]
Agreed. I didn't do it yet because all fixes in vscode since first stable release felt like small fixes and simply copying changes from the atom package to the vscode package. But theres no practical reason for it, so it's no issue to start using the minor number for the benefit of you and other devs.

I can release the next update as 1.4.0 just to align the minor with Atom.
